# Generated by Django 4.1.6 on 2023-02-09 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='n64game',
            old_name='releaseyear',
            new_name='year',
        ),
    ]
