# Generated by Django 4.1.6 on 2023-02-10 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_releaseyear_n64game_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('length', models.CharField(max_length=20)),
                ('n64game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.n64game')),
            ],
        ),
    ]
