# Generated by Django 4.1.6 on 2023-02-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_session_date_alter_session_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(verbose_name='Date of play session'),
        ),
    ]
