# Generated by Django 4.1.6 on 2023-02-10 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_session_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='length',
            new_name='hour',
        ),
    ]
