# Generated by Django 4.1.6 on 2023-02-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_length_session_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='n64game',
            name='players',
            field=models.ManyToManyField(to='main_app.player'),
        ),
    ]
